* [feature] + add option to make a gitlab merge request against $BASE_BRANCH aka mainly develop

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -236,7 +236,7 @@ F,[no]fetch      Fetch from origin before performing local operation
 
 cmd_finish() {
 	OPTIONS_SPEC="\
-git flow feature finish [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
+git flow feature finish [-m] [-h] [-F] [-r] [-p] [-k] [-D] [-S] [--no-ff] <name|nameprefix>
 
 Finish feature <name>
 --
@@ -252,6 +252,7 @@ keeplocal!             Keep the local branch
 D,[no]force_delete     Force delete feature branch after finish
 S,[no]squash           Squash feature during merge
 no-ff!                 Never fast-forward during the merge
+m,mergereq	       Do not merge feature but make a merge request
 "
 	local finish_base
 
@@ -267,6 +268,7 @@ no-ff!                 Never fast-forward during the merge
 	DEFINE_boolean 'squash' false "squash feature during merge" S
 	DEFINE_boolean 'squash-info' false "add branch info during squash"
 	DEFINE_boolean 'no-ff!' false "Don't fast-forward ever during merge "
+	DEFINE_boolean 'mergereq' false "Don't merge, but make a merge request in gitlab" m
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "feature.finish.fetch"             "fetch"
@@ -280,6 +282,7 @@ no-ff!                 Never fast-forward during the merge
 	gitflow_override_flag_boolean   "feature.finish.squash"            "squash"
 	gitflow_override_flag_boolean   "feature.finish.squash-info"       "squash_info"
 	gitflow_override_flag_boolean   "feature.finish.no-ff"             "no_ff"
+	gitflow_override_flag_boolean   "feature.finish.mergereq"          "mergereq"
 
 	# Parse arguments
 	parse_args "$@"
@@ -384,27 +387,35 @@ no-ff!                 Never fast-forward during the merge
 			exit 1
 		fi
 	fi
-
-	# Merge into BASE
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
-
-	if noflag squash; then
-		if flag no_ff; then
-			git_do merge --no-ff "$BRANCH"
-		else
-			if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-				git_do merge --ff "$BRANCH"
-			else
-				git_do merge --no-ff "$BRANCH"
-			fi
-		fi
+	if flag mergereq; then
+	    git_do commit --allow-empty -m 'finishing $BRANCH'
+	    git_do push -o merge_request.create  -o merge_request.target="$BASE_BRANCH" "$ORIGIN" "$BRANCH"
+	    echo "Finish by creating a merge request."
+	    echo "Keeping branches until merge request approuved."
+	    echo "Commit in \'$BRANCH\' to update the merge resquest"
 	else
+
+	   # Merge into BASE
+	   git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+
+
+	    if noflag squash; then
+		if flag no_ff; then
+		    git_do merge --no-ff "$BRANCH"
+		else
+		    if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+			git_do merge --ff "$BRANCH"
+		    else
+			git_do merge --no-ff "$BRANCH"
+		    fi
+		fi
+	    else
 		git_do merge --squash "$BRANCH"
 		flag squash_info && gitflow_create_squash_message "Merged feature branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
 		git_do commit
-	fi
+	    fi
 
-	if [ $? -ne 0 ]; then
+	    if [ $? -ne 0 ]; then
 		# Oops.. we have a merge conflict!
 		# Write the given $BASE_BRANCH to a temporary file as we will
 		# be needing it later.
@@ -419,13 +430,14 @@ no-ff!                 Never fast-forward during the merge
 		echo "    git flow feature finish $NAME"
 		echo
 		exit 1
+	    fi
 	fi
-
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
-
-	# When no merge conflict is detected, just clean up the feature branch
-	gitflow_config_remove_base_branch "$BRANCH"
-	helper_finish_cleanup
+	if ! flag mergereq; then
+	    # When no merge conflict is detected, just clean up the feature branch
+	    gitflow_config_remove_base_branch "$BRANCH"
+	    helper_finish_cleanup
+	fi
 }
 
 helper_finish_cleanup() {
