+ [bugfix] * add merge request to bugfix

diff --git a/git-flow-bugfix b/git-flow-bugfix
--- a/git-flow-bugfix
+++ b/git-flow-bugfix
@@ -252,6 +252,7 @@ keeplocal!             Keep the local branch
 D,[no]force_delete     Force delete bugfix branch after finish
 S,[no]squash           Squash bugfix during merge
 no-ff!                 Never fast-forward during the merge
+M,mergereq	       Do not merge feature but make a merge request
 "
 	local finish_base
 
@@ -267,6 +268,7 @@ no-ff!                 Never fast-forward during the merge
 	DEFINE_boolean 'squash' false "squash bugfix during merge" S
 	DEFINE_boolean 'squash-info' false "add branch info during squash"
 	DEFINE_boolean 'no-ff!' false "Don't fast-forward ever during merge "
+	DEFINE_boolean 'mergereq' false "Don't merge, but make a merge request in gitlab" M
 
 	# Override defaults with values from config
 	gitflow_override_flag_boolean   "bugfix.finish.fetch"             "fetch"
@@ -280,6 +282,7 @@ no-ff!                 Never fast-forward during the merge
 	gitflow_override_flag_boolean   "bugfix.finish.squash"            "squash"
 	gitflow_override_flag_boolean   "bugfix.finish.squash-info"       "squash_info"
 	gitflow_override_flag_boolean   "bugfix.finish.no-ff"             "no_ff"
+	gitflow_override_flag_boolean   "bugfix.finish.mergereq"          "mergereq"
 
 	# Parse arguments
 	parse_args "$@"
@@ -385,25 +388,36 @@ no-ff!                 Never fast-forward during the merge
 		fi
 	fi
 
-	# Merge into BASE
-	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
-
-	if noflag squash; then
-		if flag no_ff; then
-			git_do merge --no-ff "$BRANCH"
-		else
-			if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-				git_do merge --ff "$BRANCH"
-			else
-				git_do merge --no-ff "$BRANCH"
-			fi
-		fi
+	if flag mergereq; then
+	    git_do commit --allow-empty -m "finishing $BRANCH"
+	    git_do push -o merge_request.create  -o merge_request.target="$BASE_BRANCH" "$ORIGIN" "$BRANCH"
+	    echo "Finish by creating a merge request."
+	    echo "Keeping branches until merge request approuved."
+	    echo "Commit in '$BRANCH' to update the merge resquest"
+	    echo "After merge request approuval, use 'git flow finish'"
+	    echo " (wihtout -M) and 'git pull' to really finish the bugfix"
+	    exit 4
 	else
+
+	    # Merge into BASE
+	    git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
+
+	    if noflag squash; then
+		if flag no_ff; then
+		    git_do merge --no-ff "$BRANCH"
+		else
+		    if [ "$(git rev-list -n2 "$BASE_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+			git_do merge --ff "$BRANCH"
+		    else
+			git_do merge --no-ff "$BRANCH"
+		    fi
+		fi
+	    else
 		git_do merge --squash "$BRANCH"
 		flag squash_info && gitflow_create_squash_message "Merged bugfix branch '$BRANCH'" "$BASE_BRANCH" "$BRANCH" > "$DOT_GIT_DIR/SQUASH_MSG"
 		git_do commit
+	    fi
 	fi
-
 	if [ $? -ne 0 ]; then
 		# Oops.. we have a merge conflict!
 		# Write the given $BASE_BRANCH to a temporary file as we will
